import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { ThemeProvider } from "@/components/ui/providers/theme-providers";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discord-Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body className={font.className}>
        <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        forcedTheme="light"
        storageKey="theme"
        enableSystem={true}
        >
        {children}
        </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  );
}
